apiVersion: v1
kind: Service
metadata:
  name: auth-frontend # This name must match the upstream name in nginx.conf
  namespace: auth # Add namespace
  labels:
    app: auth-frontend
spec:
  selector:
    app: auth-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  # No type: LoadBalancer needed, nginx gateway will handle external access
  # Default ClusterIP is fine 