apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  labels:
    app: nginx-gateway
spec:
  selector:
    app: nginx-gateway
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80 