apiVersion: v1
kind: Service
metadata:
  name: shell # This name must match the upstream name in nginx.conf
  namespace: shell # Add namespace
  labels:
    app: shell
spec:
  selector:
    app: shell
  ports:
  - name: http
    port: 80
    targetPort: 80
  # No type: LoadBalancer needed, nginx gateway will handle external access
  # Default ClusterIP is fine 